# utils/nifty100.py

# -----------------------------------------
# NIFTY 100 Ticker List
# -----------------------------------------

NIFTY100 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "ITC.NS", "LT.NS", "SBIN.NS", "BHARTIARTL.NS", "HINDUNILVR.NS",
    "MARUTI.NS", "ASIANPAINT.NS", "KOTAKBANK.NS", "SUNPHARMA.NS", "BAJFINANCE.NS",
    "ULTRACEMCO.NS", "HCLTECH.NS", "TITAN.NS", "WIPRO.NS", "DMART.NS",
    "POWERGRID.NS", "NESTLEIND.NS", "AXISBANK.NS", "JSWSTEEL.NS", "GRASIM.NS",
    "ADANIGREEN.NS", "ADANIENT.NS", "NTPC.NS", "ONGC.NS", "COALINDIA.NS",
    "BAJAJFINSV.NS", "HEROMOTOCO.NS", "TATACONSUM.NS", "BRITANNIA.NS", "IOC.NS",
    "INDUSINDBK.NS", "DIVISLAB.NS", "EICHERMOT.NS", "TECHM.NS", "PIDILITIND.NS",
    "SBILIFE.NS", "DRREDDY.NS", "HDFCLIFE.NS", "BAJAJ-AUTO.NS", "HAVELLS.NS",
    "TATAMOTORS.NS", "ICICIPRULI.NS", "CIPLA.NS", "SHREECEM.NS", "TATAPOWER.NS",
    "M&M.NS", "ICICIGI.NS", "DLF.NS", "CHOLAFIN.NS", "TORNTPHARM.NS",
    "ADANIENSOL.NS", "BEL.NS", "APOLLOHOSP.NS", "COLPAL.NS", "JINDALSTEL.NS",
    "UPL.NS", "AMBUJACEM.NS", "HINDALCO.NS", "GAIL.NS", "BANKBARODA.NS",
    "TRENT.NS", "HAL.NS", "INDIGO.NS", "TVSMOTOR.NS", "IDFCFIRSTB.NS",
    "BERGEPAINT.NS", "PAGEIND.NS", "LODHA.NS", "NAUKRI.NS", "BPCL.NS",
    "ABFRL.NS", "LTI.NS", "ZOMATO.NS", "MOTHERSON.NS", "SRF.NS",
    "SIEMENS.NS", "ATGL.NS", "VBL.NS", "FEDERALBNK.NS", "PNB.NS",
    "BIOCON.NS", "BANDHANBNK.NS", "CANBK.NS", "VEDL.NS", "MANAPPURAM.NS",
    "RECLTD.NS", "PFC.NS", "MFSL.NS", "BAJAJHLDNG.NS", "HONAUT.NS",
    "OFSS.NS", "GLAND.NS", "IRCTC.NS", "POLYCAB.NS"
]


# -----------------------------------------
# NIFTY 100 Ticker → Company Name Mapping  
# -----------------------------------------


NIFTY100_NAMES = {
    "RELIANCE.NS": "Reliance Industries",
    "TCS.NS": "Tata Consultancy Services",
    "HDFCBANK.NS": "HDFC Bank",
    "ICICIBANK.NS": "ICICI Bank",
    "INFY.NS": "Infosys",
    "ITC.NS": "ITC",
    "LT.NS": "Larsen & Toubro",
    "SBIN.NS": "State Bank of India",
    "BHARTIARTL.NS": "Bharti Airtel",
    "HINDUNILVR.NS": "Hindustan Unilever",
    "MARUTI.NS": "Maruti Suzuki",
    "ASIANPAINT.NS": "Asian Paints",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "SUNPHARMA.NS": "Sun Pharma",
    "BAJFINANCE.NS": "Bajaj Finance",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "HCLTECH.NS": "HCL Technologies",
    "TITAN.NS": "Titan Company",
    "WIPRO.NS": "Wipro",
    "DMART.NS": "Avenue Supermarts",
    "POWERGRID.NS": "Power Grid Corporation",
    "NESTLEIND.NS": "Nestle India",
    "AXISBANK.NS": "Axis Bank",
    "JSWSTEEL.NS": "JSW Steel",
    "GRASIM.NS": "Grasim Industries",
    "ADANIGREEN.NS": "Adani Green Energy",
    "ADANIENT.NS": "Adani Enterprises",
    "NTPC.NS": "NTPC",
    "ONGC.NS": "Oil and Natural Gas Corporation",
    "COALINDIA.NS": "Coal India",
    "BAJAJFINSV.NS": "Bajaj Finserv",
    "HEROMOTOCO.NS": "Hero MotoCorp",
    "TATACONSUM.NS": "Tata Consumer Products",
    "BRITANNIA.NS": "Britannia Industries",
    "IOC.NS": "Indian Oil Corporation",
    "INDUSINDBK.NS": "IndusInd Bank",
    "DIVISLAB.NS": "Divi's Laboratories",
    "EICHERMOT.NS": "Eicher Motors",
    "TECHM.NS": "Tech Mahindra",
    "PIDILITIND.NS": "Pidilite Industries",
    "SBILIFE.NS": "SBI Life Insurance",
    "DRREDDY.NS": "Dr Reddy's Laboratories",
    "HDFCLIFE.NS": "HDFC Life Insurance",
    "BAJAJ-AUTO.NS": "Bajaj Auto",
    "HAVELLS.NS": "Havells India",
    "TATAMOTORS.NS": "Tata Motors",
    "ICICIPRULI.NS": "ICICI Prudential Life Insurance",
    "CIPLA.NS": "Cipla",
    "SHREECEM.NS": "Shree Cement",
    "TATAPOWER.NS": "Tata Power",
    "M&M.NS": "Mahindra & Mahindra",
    "ICICIGI.NS": "ICICI Lombard General Insurance",
    "DLF.NS": "DLF",
    "CHOLAFIN.NS": "Cholamandalam Investment & Finance",
    "TORNTPHARM.NS": "Torrent Pharma",
    "ADANIENSOL.NS": "Adani Energy Solutions",
    "BEL.NS": "Bharat Electronics",
    "APOLLOHOSP.NS": "Apollo Hospitals",
    "COLPAL.NS": "Colgate-Palmolive India",
    "JINDALSTEL.NS": "Jindal Steel & Power",
    "UPL.NS": "UPL",
    "AMBUJACEM.NS": "Ambuja Cements",
    "HINDALCO.NS": "Hindalco Industries",
    "GAIL.NS": "GAIL",
    "BANKBARODA.NS": "Bank of Baroda",
    "TRENT.NS": "Trent",
    "HAL.NS": "Hindustan Aeronautics",
    "INDIGO.NS": "IndiGo (InterGlobe Aviation)",
    "TVSMOTOR.NS": "TVS Motor Company",
    "IDFCFIRSTB.NS": "IDFC First Bank",
    "BERGEPAINT.NS": "Berger Paints",
    "PAGEIND.NS": "Page Industries",
    "LODHA.NS": "Macrotech Developers (Lodha)",
    "NAUKRI.NS": "Info Edge India",
    "BPCL.NS": "Bharat Petroleum",
    "ABFRL.NS": "Aditya Birla Fashion & Retail",
    "LTI.NS": "LTIMindtree",
    "ZOMATO.NS": "Eternal Ltd (formerly Zomato)",
    "MOTHERSON.NS": "Samvardhana Motherson International",
    "SRF.NS": "SRF",
    "SIEMENS.NS": "Siemens India",
    "ATGL.NS": "Adani Total Gas",
    "VBL.NS": "Varun Beverages",
    "FEDERALBNK.NS": "Federal Bank",
    "PNB.NS": "Punjab National Bank",
    "BIOCON.NS": "Biocon",
    "BANDHANBNK.NS": "Bandhan Bank",
    "CANBK.NS": "Canara Bank",
    "VEDL.NS": "Vedanta",
    "MANAPPURAM.NS": "Manappuram Finance",
    "RECLTD.NS": "REC Limited",
    "PFC.NS": "Power Finance Corporation",
    "MFSL.NS": "Max Financial Services",
    "BAJAJHLDNG.NS": "Bajaj Holdings & Investment",
    "HONAUT.NS": "Honeywell Automation India",
    "OFSS.NS": "Oracle Financial Services Software",
    "GLAND.NS": "Gland Pharma",
    "IRCTC.NS": "IRCTC",
    "POLYCAB.NS": "Polycab India"
}
